version: "3.6"

x-logging-common: &logging-common
  logging:
    options:
      max-size: "10m"
      max-file: "4"

services:
  db:
    container_name: postgres
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_PASSWORD: $DB_PASS
      POSTGRES_USER: $DB_USER
      POSTGRES_DB: $DB_NAME
    env_file:
      - ./.env
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${DB_USER} -d $${DB_NAME}"]
      interval: 1s
      timeout: 5s
      retries: 10
    restart: always
    <<: *logging-common

volumes:
  postgres_data:
